export const ACTOR_NEW_KEYWORDS = 'NEW_KEYWORDS';
export const ACTOR_SEARCH_REQUEST = 'SEARCH_REQUEST';
export const ACTOR_SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const ACTOR_SEARCH_FAIL = 'SEARCH_FAIL';
export const ACTOR_DETAILS_REQUEST = 'DETAILS_REQUEST';
export const ACTOR_DETAILS_SUCCESS = 'DETAILS_SUCCESS';
export const ACTOR_DETAILS_FAIL = 'DETAILS_FAIL';
